run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: false
  skip-dirs-use-default: true
  # skips vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  # fail when go.mod needs to be updated
  modules-download-mode: readonly
  allow-parallel-runners: false

# all available settings of specific linters
linters-settings:
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true
      
  staticcheck:
    # Select the Go version to target. The default is '1.13'.
    go: '1.12'
    # https://staticcheck.io/docs/options#checks
    checks: [all]


linters:
  disable-all: true
  enable:
  - govet
  - gosimple
  - gochecknoinits
  - gosec
  - goimports
  - asciicheck
  - typecheck
  - staticcheck
  - unused
  - forcetypeassert
  - misspell
  - noctx
  fast: false
issues: 
   new-from-rev: v1.0.1
