name: websocket
on: [push] 
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version:
        - "1.13"
        - "1.14"
        - "1.15"
        - "1.16"
        - "1.17"
        - "1.18"
        - "1.19"
        - "1.20"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test ./...
    - name: Test Race
      run: go test --race ./...
  lints:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: "1.20"
    - uses: actions/checkout@v3
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.51.2
        only-new-issues: true
